language: go

go:
- 1.12.x

# Only clone the most recent commit.
git:
  depth: 1

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - GO111MODULE=on go mod vendor
  - golangci-lint run       # run a bunch of code checkers/linters in parallel
  - go test -v -race ./...  # Run all the tests with the race detector enabled