language: go

go:
- 1.14.x

# Only clone the most recent commit.
git:
  depth: 1

# Get (and start) mongodb for unit tests
services:
  - mongodb

script:
  - GO111MODULE=on go mod vendor
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...  # Run all the tests with the race detector enabled

after_success:
  - bash <(curl -s https://codecov.io/bash)