language: go

go:
- 1.12.x

# Only clone the most recent commit.
git:
  depth: 1

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.20.1

script:
  - GO111MODULE=on go mod vendor
  - golangci-lint run -v    # run a bunch of code checkers/linters in parallel
  - go test -v -race ./...  # Run all the tests with the race detector enabled
