name: client-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: stefanoeb/eslint-action@1.0.2
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: eslint ./client --ext .js,.jsx,.ts,.tsx
