name: client-lint
defaults:
  run:
    working-directory: client
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install npm packages
        run: npm install
      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx
