name: client-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        working-directory: client
      - name: Install ESLint
        uses: stefanoeb/eslint-action@1.0.2
        working-directory: client
      - name: Install modules
        run: yarn
        working-directory: client
      - name: Run ESLint
        run: eslint ./client --ext .js,.jsx,.ts,.tsx
        working-directory: client
